name: taxi_driver
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # BASE
  intl: ^0.19.0
  google_fonts: ^6.2.1
  html: ^0.15.4
  shared_preferences: ^2.3.2
  flutter_widget_from_html: ^0.15.2
  # TOAST
  fluttertoast: ^8.2.8
  # IMAGE
  cached_network_image: ^3.3.1
  # UI
  sliding_up_panel: ^2.0.0+1
  dotted_line: ^3.2.2
  lottie: ^3.3.1
  flutter_rating_bar: ^4.0.1
  flutter_staggered_animations: ^1.1.1
  bottom_picker: ^2.8.0
  country_code_picker: ^3.0.0
  flutter_native_contact_picker: ^0.0.10
  timeline_tile: ^2.0.0
  flutter_vector_icons: ^2.0.0
  syncfusion_flutter_charts: ^26.2.11
  #OTP TEXT FIELD
  pinput: ^5.0.0
  #MAP
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  google_maps_flutter: ^2.9.0
  flutter_polyline_points:
    git:
      url: https://github.com/appmeetmighty/flutter_polyline_points.git
  location: ^7.0.0
  #IMAGES
  image_picker: ^1.2.0
  file_picker: ^8.0.6
  date_time_picker: ^2.1.0
  #CONNECTIVITY
  package_info_plus: ^8.0.2
  http: ^1.2.2
  connectivity_plus: ^6.0.5
  url_launcher: ^6.3.0
  map_launcher: ^3.5.0
  internet_file: ^1.2.0
  #FIREBASE
  firebase_core: ^4.1.1
  firebase_analytics: ^12.0.2
  firebase_crashlytics: ^5.0.2
  cloud_firestore: ^6.0.2
  firebase_storage: ^13.0.2
  firebase_messaging: ^16.0.2
  firebase_auth: ^6.1.0
  firebase_database: ^12.0.2
  paginate_firestore:
    git:
      url: https://github.com/Gosplex/paginate_firestore.git
  #STATE MANAGEMENT
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  #PAYMENT GATEWAY
  razorpay_flutter: ^1.3.7
  flutter_stripe: ^11.0.0
  flutterwave_standard_smart: ^1.0.4
  flutter_paytabs_bridge: ^2.6.17
  my_fatoorah: ^3.3.0
  flutter_paystack:
    git:
      url: https://github.com/appmeetmighty/flutter_paystack.git
#  flutter_braintree_betc:
#    git:
#      url: https://github.com/appmeetmighty/flutter-braintree.git
  flutter_braintree_payment: ^1.1.0
  rxdart: ^0.28.0
  # PUSH NOTIFICATION
  onesignal_flutter: ^5.2.4
  #SOCIAL LOGIN
  google_sign_in: ^6.2.1
  the_apple_sign_in: ^1.1.1
  flutter_image_compress: ^2.3.0
  #DOWNLOAD INVOICE PDF
  pdf: ^3.11.1
  pdfx: 2.6.0
  path_provider: ^2.1.4
  open_file: ^3.5.3
  flutter_ringtone_player: ^4.0.0+3
  permission_handler:
  flutter_paypal_payment:
  share_plus:
  dotted_border: ^2.1.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.11
  mobx_codegen: ^2.6.1
  #flutter packages pub run build_runner build --delete-conflicting-outputs

dependency_overrides:
  image_picker_android: 0.8.12+23
  video_player_android: 2.8.2
  intl: ^0.18.0
  http: ^0.13.5
  package_info_plus: ^4.1.0
  stripe_android: 11.4.0
  google_maps_flutter_android: 2.16.1



flutter:

  uses-material-design: true

  assets:
    - images/
    - images/icons/
    - images/json_files/
    - images/app_images/
    - images/ringtone.mp3
    - staticjson/


